# config.py
BG_COLOR = "#9DBABA"  
BTN_COLOR = "#59999A"
BTN_TEXT_COLOR = "white"
ENTRY_BG = "#222222"
ENTRY_FG = "white"
LABEL_TEXT_COLOR = "white"
HIGHLIGHT_COLOR = "yellow"
INSERT = "white"
FONT_FAMILY = "Roboto"
FONT_SIZE = 12
FONT = (FONT_FAMILY, FONT_SIZE)